config/routes.rb
Recon2::Application.routes.draw do  resources :notes
  resources :phases
  resources :categories
  resources :pages


  get "sessions/new"
  get "users/new"
  get "pages/graphe"
  get "pages/home"
  get "pages/graphe"

 

  match '/signup',  :to => 'users#new', via: 'get'
  get '/signin',  :to => 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get '/contact', :to => 'pages#contact'
  get '/about',   :to => 'pages#about'
  get '/help',    :to => 'pages#help'
  match '/graphe', :to => 'pages#graphe', via: 'get'
  
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  root :to => 'pages#home'
  










end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
  # GET /phases
  # GET /phases.json
  def index
    @phases = Phase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phases }
    end
  end

  # GET /phases/1
  # GET /phases/1.json
  def show
    @phase = Phase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phase }
    end
  end

  # GET /phases/new
  # GET /phases/new.json
  def new
    @phase = Phase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phase }
    end
  end

  # GET /phases/1/edit
  def edit
    @phase = Phase.find(params[:id])
  end

  # POST /phases
  # POST /phases.json
  def create
    @phase = Phase.new(params[:phase])

    respond_to do |format|
      if @phase.save
        format.html { redirect_to @phase, notice: 'Phase was successfully created.' }
        format.json { render json: @phase, status: :created, location: @phase }
      else
        format.html { render action: "new" }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phases/1
  # PUT /phases/1.json
  def update
    @phase = Phase.find(params[:id])

    respond_to do |format|
      if @phase.update_attributes(params[:phase])
        format.html { redirect_to @phase, notice: 'Phase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phases/1
  # DELETE /phases/1.json
  def destroy
    @phase = Phase.find(params[:id])
    @phase.destroy

    respond_to do |format|
      format.html { redirect_to phases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/views/phases/_form.html.erb
<%= form_for(@phase) do |f| %>
  <% if @phase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phase.errors.count, "error") %> prohibited this phase from being saved:</h2>

      <ul>
      <% @phase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phases/edit.html.erb
<h1>Editing phase</h1>

<%= render 'form' %>

<%= link_to 'Show', @phase %> |
<%= link_to 'Back', phases_path %>

app/views/phases/index.html.erb
<h1>Listing phases</h1>

<table>
  <tr>
    <th>Nom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phases.each do |phase| %>
  <tr>
    <td><%= phase.nom %></td>
    <td><%= link_to 'Show', phase %></td>
    <td><%= link_to 'Edit', edit_phase_path(phase) %></td>
    <td><%= link_to 'Destroy', phase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phase', new_phase_path %>

app/views/phases/new.html.erb
<h1>New phase</h1>

<%= render 'form' %>

<%= link_to 'Back', phases_path %>

app/views/phases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @phase.nom %>
</p>


<%= link_to 'Edit', edit_phase_path(@phase) %> |
<%= link_to 'Back', phases_path %>