config/routes.rb
Recon2::Application.routes.draw do  resources :notes
  resources :phases
  resources :categories
  resources :pages


  get "sessions/new"
  get "users/new"
  get "pages/graphe"
  get "pages/home"
  get "pages/graphe"

 

  match '/signup',  :to => 'users#new', via: 'get'
  get '/signin',  :to => 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get '/contact', :to => 'pages#contact'
  get '/about',   :to => 'pages#about'
  get '/help',    :to => 'pages#help'
  match '/graphe', :to => 'pages#graphe', via: 'get'
  
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  root :to => 'pages#home'
  










end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Iut Montpellier-Sete", "http://www.iutmontp.univ-montp2.fr/" %></li>
      <li><%= link_to "UM2", "http://www.univ-montp2.fr/" %></li>
      <li><%= link_to "ENT", "http://portail.univ-montp2.fr/"%></li>
      <li><%= link_to "Intranet", "http://iutdepinfo.iutmontp.univ-montp2.fr/"%></li>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
	  <%= image_tag "logoiut.jpg" %> 
  </nav>
  <nav class="round">
	  <ul class="semiopaquemenu">
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Saisir Note", new_note_path %></li>
      <li><%= link_to "Mon Carnet", notes_path %></li>
      <li><%= link_to "Mes Categories", categories_path %></li>
       <li><%= link_to "Voir Graphe", graphe_path %></li>
      <li><%= link_to "Profil", edit_user_path(current_user) %></li>
      <li><%= link_to "Logout", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Login", signin_path %></li>
      <% end %>
    </ul>
    <div 
			class="bottombar">
	</div>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag "menu" %>
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<%# -*- coding: UTF-8 -*- %>
<!DOCTYPE html>
<html>
  <head>
  	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><%= title %></title>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>